### ISSUE TITLE
FoundCrate::Itself reported in doc tests

### ISSUE THREAD

**Issue by h33p** [bkchr/proc-macro-crate#11]
Hey there, it appears that `FoundCrate::Itself` is being returned when inside documentation tests. I currently work this around with the following snippet:

```rust
pub fn crate_path() -> TokenStream {
    let found_crate = crate_name("cglue").expect("cglue found in `Cargo.toml`");

    match found_crate {
        FoundCrate::Itself => {
            let has_doc_env = std::env::vars().any(|(k, _)| {
                k == "UNSTABLE_RUSTDOC_TEST_LINE" || k == "UNSTABLE_RUSTDOC_TEST_PATH"
            });

            if has_doc_env {
                quote!(::cglue)
            } else {
                quote!(crate)
            }
        }
        FoundCrate::Name(name) => quote!(::#name),
    }
}
```

Now, these environment variables are clearly not stable, but it was the only way I could distinguish doc tests, sooooo I don't know, the worst that could happen is these variables being removed.

**Comment by bkchr** [comment]
Hey,
sadly there isn't anything I can do here. There is nothing to detect if this is a doc test or not.

The best is to do the following: 
```
extern crate self as cglue;
```

**Comment by SoftwareSheriff** [comment]
You could use your own environment variable, for example `DOCTEST_MODE`, and then run your CI like this:
```bash
cargo test --tests # everything except doctests
DOCTEST_MODE="" cargo test --doc # only doctests
```
Since https://github.com/bkchr/proc-macro-crate/pull/13,  you could also just use `proc-macro-crate` as normal, and use the above snippet in CI except with the `CARGO_TARGET_TMPDIR` environment variable.

**Comment by jplatte** [comment]
> Hey, sadly there isn't anything I can do here. There is nothing to detect if this is a doc test or not.
> 
> The best is to do the following:
> 
> ```
> extern crate self as cglue;
> ```

But that only works if ones emits the crate name on `FoundCrate::Itself`, which defeats the purpose of that enum variant. I feel like this should be re-opened (with a `blocked` label potentially`) and only closed once it is possible (through Cargo / rustc changes) to make this work.

**Comment by bkchr** [comment]
I mean this entire crate is a hack around some missing feature in rustc :P I somehow still hope that rustc at some day brings "native" support for this.
