### ISSUE TITLE
Mininum Rust version policy?

### ISSUE THREAD

**Issue by jasonish** [bkchr/proc-macro-crate#17]
Curious if there is any cocern to a minimum supported Rust version?  We just noticed that going from 1.1.0 to 1.1.2 upped the minimum Rust version from 1.45 (or older) to 1.53.

https://github.com/OISF/suricata/pull/7019

Thanks.

**Comment by bkchr** [comment]
Ohhh, what is the error below 1.53? I mean this wasn't broken on purpose.

**Comment by bkchr** [comment]
@jasonish do you need support for rust 1.52? If yes, I can fix this and release another patch release.

**Comment by CriesofCarrots** [comment]
> I can fix this and release another patch release.

One "yes, please" vote from us! [solana-labs/solana:v1.8](https://github.com/solana-labs/solana/tree/v1.8) is pinned to rust v1.52, and this broke our release CI.

**Comment by jasonish** [comment]
> @jasonish do you need support for rust 1.52? If yes, I can fix this and release another patch release.

We still target 1.48 as we try to keep our builds working on the Rust versions included in the most popular distributions as seen here: https://redmine.openinfosecfoundation.org/issues/4163

**Comment by bkchr** [comment]
Sorry for the problems!

I added now CI which ensures that it compiles with rust 1.42.0. I yanked the 1.1.2 and released 1.1.3 :)

**Comment by jasonish** [comment]
Awesome. Thanks!
