### ISSUE TITLE
Feature request: Cache result of reading `Cargo.toml`

### ISSUE THREAD

**Issue by jplatte** [bkchr/proc-macro-crate#19]
I think it would be very nice if multiple macro invocations inside one crate that all use `proc-macro-crate` wouldn't all individually read and parse `Cargo.toml`. Would you be open to a PR that caches the result of reading the manifest file (using the `once_cell` crate)?

**Comment by bkchr** [comment]
Do you think it brings that much extra performance? If you like, you can create a pr.

**Comment by jplatte** [comment]
I'm not sure about performance, but in general I think minimizing I/O is a good idea.

I'll create a PR then 🙂

**Comment by bkchr** [comment]
But why introduce complexity for no benefit?

**Comment by jplatte** [comment]
I think it can only be better for perf, and reliability. I'll make sure to benchmark when I've implemented the change.
