### ISSUE TITLE
Crate name not detected from within itself

### ISSUE THREAD

**Issue by CJKay** [bkchr/proc-macro-crate#2]
When using a proc-macro that uses `crate_name()`, `crate_name()` cannot detect the crate name if it is the current crate.

**Comment by bkchr** [comment]
Hey,
yeah that is correct, but that would not help you. As, when you want to import `my-crate` and you are in `my-crate`, you can not write `my-crate::something`. So, we solve this outside of this crate in the following way:
```
	if env::var("CARGO_PKG_NAME").unwrap() == "my-crate" {
		TokenStream::new()
	} else {
		match crate_name("my-crate") {
			Ok(crate_name) => {
				let crate_name = Ident::new(&crate_name, Span::call_site());
				quote!(
					#[doc(hidden)]
					extern crate #crate_name as proc_macro_runtime_interface;
				)
			},
			Err(e) => {
				let err = Error::new(Span::call_site(), &e).to_compile_error();
				quote!( #err )
			}
		}
	}
```

(You can actually also use `my-crate` as identifier inside of `my-crate`, but then you need to add to your `lib.rs`: `extern crate self as my_crate;`)

**Comment by CJKay** [comment]
Is there no way this can be done in the `crate_name()`? I don't know what `${CARGO_PKG_NAME}` holds if you are the dependency of a proc-macro crate, whether it's the name of the proc-macro caller crate, the proc-macro implementation crate, or just `crate-name`.

What would be great is if it could return `crate` so that we could do things like the following:

```
lazy_static! {
    static ref CRATE_NAME: String = crate_name("my-crate");
}

...

quote! { #CRATE_NAME::MyType { ... } /* `crate::MyType` or `my_crate::MyType` */ }
```

**Comment by bkchr** [comment]
That sadly does not work. As in tests in the tests directory you also get the crate name of your crate in the env variable, but you can not use `crate` to access stuff in your own crate, you need to use the full identifier.

**Comment by CJKay** [comment]
That's a real shame. I suppose this crate is really a workaround for more fundamental issues anyway, so I'll close this out - thanks!

**Comment by bkchr** [comment]
Ty, good that you like it :)
