### ISSUE TITLE
Switch to toml_edit from toml-rs

### ISSUE THREAD

**Issue by Shatur** [bkchr/proc-macro-crate#25]
## What problem does this solve or what need does it fill?

[toml-rs](https://github.com/alexcrichton/toml-rs) is [unmaintained](https://github.com/alexcrichton/toml-rs/issues/460) and it's a TOML 0.5 compliant parser.

## What solution would you like?

It would be nice to use [toml_edit](https://github.com/ordian/toml_edit). It's a drop-in replacement, actively maintained and supports TOML 1.0. For example, [Cargo now use it](https://github.com/rust-lang/cargo/pull/10086).

**Comment by Shatur** [comment]
[toml-rs](https://github.com/toml-rs/toml-rs) was archived. @bkchr are you interested in this change? I could send a PR. It basically a drop-in replacement.

**Comment by bkchr** [comment]
Yes! Sorry for having overseen this!

**Comment by Shatur** [comment]
@bkchr opened #29.
