### ISSUE TITLE
Version 1.2.x changes behaviour

### ISSUE THREAD

**Issue by vmx** [bkchr/proc-macro-crate#26]
I've a problem with upgrading from 1.1.3 to version 1.2.1. Here are the steps to reproduce the problem.

```console
git clone https://github.com/multiformats/rust-multihash.git --branch v0.16.3
cd rust-multihash
cargo build
cargo update --package proc-macro-crate
cargo build
```

The build fails, due to `crate_name()` returning `Ok(FoundCrate::Name("multihash"))` instead of `Ok(FoundCrate::Itself)` (https://github.com/multiformats/rust-multihash/blob/v0.16.3/derive/src/utils.rs#L8-L11).

You can see the difference in the output via `cargo expand multihash_impl`.

**Comment by vmx** [comment]
Thanks a lot for the fix, it fixes my issue!

**Comment by bkchr** [comment]
NP! I tested it with your repo :D
