### ISSUE TITLE
Build failure in `vendor` dir

### ISSUE THREAD

**Issue by ggwpez** [bkchr/proc-macro-crate#48]
Fails to build after doing a `cargo vendor` in one downstream repo, eg: https://github.com/polkadot-fellows/runtimes  
I think its this line:  https://github.com/bkchr/proc-macro-crate/blob/c9671b5f8c307c50aab61e2352450a620d236d8b/src/lib.rs#L255  

Can it just use a mocked timestamp or something?

Example error from the repo above:  
```pre
error: Could not find `Cargo.toml` in manifest dir: ``.
   --> runtimes/vendor/scale-info/src/ty/mod.rs:527:61
    |
527 | #[cfg_attr(any(feature = "std", feature = "decode"), derive(scale::Decode))]
    |                                                             ^^^^^^^^^^^^^
    |
    = note: this error originates in the derive macro `scale::Decode` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by jplatte** [comment]
Does it help to change

```rust
let manifest_dir = env::var("CARGO_MANIFEST_DIR").map_err(|_| Error::CargoManifestDirNotSet)?;
```

to

```rust
let mut manifest_dir = env::var("CARGO_MANIFEST_DIR").map_err(|_| Error::CargoManifestDirNotSet)?;
if manifest_dir.is_empty() {
    manifest_dir = ".".to_owned();
}
```

**Comment by ggwpez** [comment]
Thanks for the hint!  
Maybe its something with the CWD, since the `CARGO_MANIFEST_DIR` is correctly set to the dependency dir, that also contains a `Cargo.toml`. i will try to see whats wrong.

**Comment by ggwpez** [comment]
I guess its one of the subsequent calls to to `cargo_toml_timestamp` and not the first one, since `CARGO_MANIFEST_DIR` looks good.
