### ISSUE TITLE
Problem when building under Bazel

### ISSUE THREAD

**Issue by blind-oracle** [bkchr/proc-macro-crate#53]
Somewhere deep in my dep tree I found this crate and it fails to build :)

Since the Bazel does not set the `CARGO` env (and it does not use `cargo` at all I think?) this macro fails. Any idea if there might be any workaround? Adding some fake `CARGO` env that points to *some* cargo binary?

Thanks in advance.

**Comment by bkchr** [comment]
I never used Bazel. Do they at least set things like `CARGO_MANIFEST_DIR`? 

Just using a fake `cargo` binary will not work. It will use [`locate-project`](https://github.com/bkchr/proc-macro-crate/blob/a5939f3fbf94279b45902119d97f881fefca6a0d/src/lib.rs#L245) to find the workspace `Cargo.toml`, which I assume does not exist for Bazel. I mean the entire crate builds around the assumption that there exists a `Cargo.toml`, which is probably not the case for Bazel?

So, the crate at all probably doesn't work with Bazel?

**Comment by blind-oracle** [comment]
Thanks for the reply. Yes, I figured as much. Thing is that the problem started when some of the crates that depend on `proc-macro-crate` bumped it from v1 to v3, so I guess v1 was different and didn't require `cargo` binary.

Anyway, we'll have to figure out some workarounds. Thanks again!
